apiVersion: v1
kind: Service
metadata:
  name: example-service-ci
  labels:
    app: example-service-ci
spec:
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: example-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-deployment-ci
  labels:
    app: example-deployment-ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app-ci
    spec:
      containers:
      - name: example-container-ci
        image: zlabjp/docker-example:release-0.1.0
        ports:
        - containerPort: 4000
